### ISSUE TITLE
Problem attaching to fully erased STM32F1xx

### ISSUE THREAD

**Issue by gsmcmullin** [blacksphere/blackmagic#5] opened 2012-07-30 07:47 UTC
Users have reported problems attaching to STM32F1xx with totally erased flash.
The probe stops responding after receiving the vAttach packet.

**Comment by esden** [comment] 2017-02-23 23:42
Is that still an issue or should we close it? Or are we keeping that open in case someone runs into this issue?

**Comment by esden** [comment] 2017-04-12 20:59
As we can't reproduce this I am moving this milestone to V1.7

**Comment by esden** [comment] 2021-12-15 19:26
As this issue was open for very long I am closing this. If this is still an issue for someone please feel free to reopen.

**Closed by esden** 2021-12-15 19:26 UTC
Labels: Bug, Can't reproduce
